name: CI pipeline

on:
    push:
        branches: [main]                          # Trigger the workflow on pushes to the main branch


jobs:
    build_push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4                # Check out the repository code to the runner
            
            - name: set up Docker Buildx
              uses: docker/setup-buildx-action@v4      # Set up Docker Buildx for building the application.


            